js1-1
nishi0225/JavaScript pull request #1
Opened 2020-09-21 03:52 UTC by nishi0225

2020-09-22 00:38 UTC, kouki-iwahara commented on index.html
> +    for(let i=1; i<100; i++) {
以下のようにスペースを空けましょう。
```
for(let i = 1; i < 100; i++) {
```
他にもスペースが無い箇所がありますので修正しましょう。

2020-09-22 00:38 UTC, kouki-iwahara commented on index.html
> +      if( i % 3 === 0 && i % 5 != 0) {
`!=`を`!==`としましょう。
JSでは必ず厳密(不)等価演算子を使用してください。

2020-09-26 13:49 UTC, myzktkyk approved these changes
特に問題ありません！

2020-11-03 12:46 UTC, myzktkyk commented on js_1_4.html
> +        content:content,
```suggestion
        content:content,
```

2020-11-03 12:54 UTC, myzktkyk requested changes
何点か指摘をしています。

2020-11-03 12:54 UTC, myzktkyk commented on js_1_4.html
> +    }
以下のように少し省略しても良いかなと思いました。
```suggestion
    const taskAdd = (genre, content) => {
        taskList.push({
            genre: genre,
            content: content,
        });
    }
```

2020-11-03 12:54 UTC, myzktkyk commented on js_1_4.html
> +      })
ちょっと冗長に感じたので、こんな感じにすっきりさせても良いかなと思いました。
```suggestion
      taskList.forEach((task, index) => {
        console.log(`${index}:[内容]${task.content},[ジャンル]${task.genre}`);
      })
```

2020-11-03 12:54 UTC, myzktkyk commented on js_1_4.html
> +
2行以上の空行はコードの行数が必要以上に増え、見にくくなるので控えた方がよいです。

2020-11-06 02:13 UTC, niganium reviewed
確認しました。
問題ありません！以下細かい指摘です！

2020-11-06 02:13 UTC, niganium commented on js_1_4.html
> +    const adding_task = prompt('タスクを入力してください');
2つの変数はキャメルケースにした方が良いと思います。

2020-11-19 00:52 UTC, niganium reviewed
何点か指摘をしました。修正したのち再提出をお願いいたします。

2020-11-19 00:52 UTC, niganium commented on js/index.js
> +  if(Number.isInteger(Number(fizNum)) && Number.isInteger(Number(buzNum))) {
ifやfor文にはスペースを設けましょう

2020-11-19 00:52 UTC, niganium commented on js/index.js
> +  if(Number.isInteger(Number(fizNum)) && Number.isInteger(Number(buzNum))) {
片方がエラーの場合はエラー+片方の掛け算が出力されます。
どちらかがエラーの場合はエラー文のみ出しましょう
また空欄の時もエラーが出るようにしてください

2020-11-19 00:52 UTC, niganium commented on js/index.js
> +  for(let i = 1; i < 100; i++) {
エラーが出ない場合に限りループを実行させるような処理にするといらぬ処理が走らずに済むと思います

2020-11-23 01:38 UTC, kouki-iwahara reviewed
コメントしましたのでご確認ください。

2020-11-23 01:38 UTC, kouki-iwahara commented on js/index.js
> +  const noText = "";
文字列は''で統一しましょう。

2020-11-23 01:38 UTC, kouki-iwahara commented on js/index.js
> +  if (!Number.isInteger(Number(fizNum)) || !Number.isInteger(Number(buzNum)) || fizNum === noText || buzNum === noText) {
noTextですが、空文字を変数に格納して使用するようなことはあまりしません。
なので、
`fizNum === ''`
で良いです。

また設計としては、バリデーションに引っ掛かったらエラーを出力し、通過したら処理を実行する、という方が良いです。
以下のイメージです。
```
if(バリデーションの条件) {
　validation_error();
　return
}
for (let i = 1; i < 100; i++) {}
```

2020-11-23 01:38 UTC, kouki-iwahara commented on js/index.js
>  const validation_error = () => {
キャメルケースで命名しましょう。

2021-02-17 07:32 UTC, merged